### PR TITLE
Fix for in loops to guard against added prototype methods

### PR DESCRIPTION
**Pull request by marmite22**
We use your plug in and this was causing an error in our codebase because someone had extended Arrays with a custom prototype :(

See http://www.jameswiseman.com/blog/2011/04/07/jslint-messages-the-body-of-a-for-in-should-be-wrapped-in-an-if-statement/

I'm afraid I don't know what method/build process you use to minify the JS so I've not updated the .min.js file.

### CODE REVIEW

**Comment by swashata** [comment]
I maybe a bit out of loop here, but isn't extending prototype is forbidden with jQuery? https://bugs.jquery.com/ticket/2721

**Comment by marmite22** [comment]
I agree we definitely shouldn't be doing it! Someone has though somewhere in our code base - they will be beaten. I've just added some checks to guard against it and make fontIconPicker more robust.

**Comment by swashata** [comment]
But fip is a jQuery plugin which shouldn't check against any practice the jQuery explicitly tells not to do. Let's cc @micc83 and hear from him.

**Comment by swashata** [comment]
Closing issue, since the idea doesn't go well with the framework.

**Pull request closed without merging**
